
import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {Check,Copy,FileUp,Loader2,ShieldCheck,Sparkles} from 'lucide-react';
import {supabase} from '@/lib/supabase';
import {useAuth} from '@/context/AuthContext';
export function Pricing(){const{user,profile}=useAuth();const[upi,setUpi]=useState('dhalak65@okicici');const[qr,setQr]=useState('');const[sales,setSales]=useState('');const[plan,setPlan]=useState<'unlimited'|'business'>('unlimited');const[tx,setTx]=useState('');const[file,setFile]=useState<File|null>(null);const[sending,setSending]=useState(false);const[msg,setMsg]=useState('');
 useEffect(()=>{
  const load=async()=>{
    const fallback='dhalak65@okicici';
    let payee=fallback; let amount=199;
    const {data}=await supabase.from('app_settings').select('value').eq('key','payment').maybeSingle();
    const v=data?.value as any;
    if(v?.upi_id) payee=v.upi_id;
    if(v?.unlimited_price) amount=Number(v.unlimited_price);
    setUpi(payee); setPlan('unlimited');
    try{const url=await QRCode.toDataURL(`upi://pay?pa=${encodeURIComponent(payee)}&pn=${encodeURIComponent('QuadraFroyn Solutions')}&am=${amount}&cu=INR`,{width:360,margin:2,errorCorrectionLevel:'M'});setQr(url)}catch(e){setMsg('Could not generate the payment QR. Please refresh the page.')}
  };
  load();
 },[]);
 const submit=async()=>{if(plan==='business'){setMsg(sales?'Sales contact request noted. Please use your configured sales email.':'Business plan is a contact-sales plan. Ask an administrator to configure a sales contact.');return} if(!user||!file||!tx||!upi){setMsg('Enter the transaction ID and upload payment proof.');return}setSending(true);try{const path=`${user.id}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const up=await supabase.storage.from('payment-proofs').upload(path,file,{upsert:false});if(up.error)throw up.error;const{error}=await supabase.from('payment_submissions').insert({user_id:user.id,plan,transaction_id:tx.trim(),proof_path:path,amount:plan==='unlimited'?199:0});if(error)throw error;setMsg('Submitted. Your package activates after admin approval.')}catch(e){setMsg(e instanceof Error?e.message:'Submission failed')}finally{setSending(false)}};
 return <div className="max-w-5xl mx-auto space-y-7 reveal"><div className="text-center"><span className="text-xs uppercase tracking-[.22em] text-[#3047ff] font-bold">Plans</span><h1 className="text-4xl font-extrabold mt-3">Choose your career operating system.</h1><p className="text-sm text-[#697086] mt-2">Free credits renew automatically. Unlimited is activated after your payment is manually verified.</p></div>
 <div className="grid md:grid-cols-3 gap-4"><Plan title="Free"price="₹0"desc="For trying the studio."items={['5 total tool actions / month','Resume history & exports','Credits renew automatically']}active={profile?.plan==='free'}/><Plan title="Unlimited"price="₹199"desc="For serious job seekers."items={['Unlimited AI resume builder','Unlimited ATS & career tools','All templates & workspace tools','Priority feature access']}active={profile?.plan==='unlimited'}featured onClick={()=>setPlan('unlimited')}/><Plan title="Business"price="25 +"desc="Let’s talk"items={['Scalable team solutions','Customized pricing','Admin & business workflows','Dedicated support']}active={profile?.plan==='business'}onClick={()=>setPlan('business')}/></div>
 <div className="card p-6"><div className="flex flex-col md:flex-row gap-8"><div className="md:w-1/2"><h2 className="font-extrabold text-xl">Pay securely by QR</h2><p className="text-sm text-[#697086] mt-2">Scan with GPay or PhonePe. The merchant name is always shown as <b>QuadraFroyn Solutions</b>. No Razorpay, Cashfree or other payment gateway is used.</p>{upi?<div className="mt-5"><div className="bg-[#f7f8fb] rounded-2xl p-4 inline-block"><img src={qr} className="w-64 h-64" alt="QuadraFroyn Solutions UPI QR"/></div><p className="text-xs text-[#8b91a3] mt-2">Payee: <b>QuadraFroyn Solutions</b> · UPI ID: {upi}</p><button className="btn btn-soft mt-3" onClick={()=>navigator.clipboard.writeText(upi)}><Copy size={14}/> Copy UPI ID</button></div>:<div className="mt-5 p-4 rounded-xl bg-amber-50 text-amber-800 text-sm">Payment QR is not configured yet. An administrator needs to add the official UPI ID.</div>}</div>
 <div className="flex-1"><h3 className="font-extrabold">After payment</h3><div className="space-y-3 mt-4"><label className="text-xs font-bold">Selected package<select className="field mt-1" value={plan} onChange={e=>setPlan(e.target.value as any)}><option value="unlimited">Unlimited — ₹199</option><option value="business">Business — contact sales</option></select></label><div className="rounded-xl bg-[#f7f8fb] p-3 text-xs text-[#697086]">Business is a custom <b>Let’s talk</b> package. No QR payment is required for Business.</div>{plan==='business'?<div className="rounded-xl border border-[#e7e9f0] p-4"><p className="text-sm font-bold">Business solutions</p><p className="text-xs text-[#697086] mt-1">For teams, colleges and hiring programs, contact the QuadraFroyn Solutions sales team through your configured support channel.</p></div>:<><label className="text-xs font-bold">Transaction ID<input className="field mt-1" value={tx} onChange={e=>setTx(e.target.value)} placeholder="Enter your UTR / transaction ID"/></label><label className="text-xs font-bold">Payment proof<input type="file" accept="image/*,.pdf" className="field mt-1" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></>}<button disabled={sending||plan==='business'} onClick={submit} className="btn btn-primary w-full">{sending?<Loader2 size={15} className="animate-spin"/>:<ShieldCheck size={15}/>} Submit for admin approval</button>{msg&&<p className="text-sm text-[#3047ff]">{msg}</p>}</div></div></div></div>
 </div>}
function Plan({title,price,desc,items,active,featured,onClick}:{title:string;price:string;desc:string;items:string[];active?:boolean;featured?:boolean;onClick?:()=>void}){return <button onClick={onClick} className={`text-left rounded-2xl p-6 border ${featured?'bg-[#04042c] text-white border-[#04042c] shadow-xl':'bg-white border-[#e7e9f0]'} ${active?'ring-2 ring-[#3047ff]':''}`}><div className="flex justify-between"><p className="font-extrabold">{title}</p>{active&&<span className="text-[9px] uppercase tracking-wider px-2 py-1 rounded-full bg-[#3047ff] text-white">Current</span>}</div><p className="text-3xl font-extrabold mt-6">{price}{title==='Unlimited'&&<small className="text-xs font-medium opacity-60"> / month</small>}</p><p className={`text-xs mt-1 ${featured?'text-white/50':'text-[#8b91a3]'}`}>{desc}</p><ul className="space-y-2 mt-6">{items.map(x=><li key={x} className="text-xs flex gap-2"><Check size={14} className="shrink-0 text-[#3047ff]"/>{x}</li>)}</ul></button>}
