import { useEffect, useState } from 'react';
import { Save, Shield, UserRound, Bell, KeyRound, Check, Eye, EyeOff, Download, Trash2 } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { supabase } from '@/lib/supabase';
import { useResumes } from '@/context/ResumeContext';

export function Settings(){
  const {profile,updateProfile,user}=useAuth(); const {resumes}=useResumes();
  const [tab,setTab]=useState<'profile'|'notifications'|'privacy'|'security'>('profile');
  const [form,setForm]=useState({full_name:'',phone:'',location:'',job_title:''});
  const [saved,setSaved]=useState(false); const [notice,setNotice]=useState('');
  const [notify,setNotify]=useState({product:true,weekly:true,marketing:false});
  const [privacy,setPrivacy]=useState({analytics:true,aiTraining:false,publicSharing:false});
  const [showPass,setShowPass]=useState(false); const [password,setPassword]=useState('');
  useEffect(()=>{if(profile){setForm({full_name:profile.full_name||'',phone:profile.phone||'',location:profile.location||'',job_title:profile.job_title||''});const p=profile.preferences||{};if(p.notifications)setNotify(v=>({...v,...p.notifications}));if(p.privacy)setPrivacy(v=>({...v,...p.privacy}))}},[profile]);
  const save=async()=>{try{await updateProfile(form);setSaved(true);setTimeout(()=>setSaved(false),1800)}catch(e){setNotice(e instanceof Error?e.message:'Could not save profile')}};
  const savePrefs=async()=>{try{await updateProfile({preferences:{notifications:notify,privacy}} as any);setNotice('Preferences saved')}catch(e){setNotice(e instanceof Error?e.message:'Could not save preferences')}};
  const exportData=()=>{const blob=new Blob([JSON.stringify({profile,resumes},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='quadraresume-account-export.json';a.click();URL.revokeObjectURL(url)};
  const changePassword=async()=>{if(password.length<8){setNotice('Use a password with at least 8 characters.');return}const{error}=await supabase.auth.updateUser({password});if(error)setNotice(error.message);else{setPassword('');setNotice('Password updated successfully')}};
  const tabs=[['profile','Profile',UserRound],['notifications','Notifications',Bell],['privacy','Privacy',Shield],['security','Security',KeyRound]] as const;
  return <div className="max-w-5xl mx-auto space-y-6 reveal"><div><p className="text-xs uppercase tracking-[.2em] text-[#3047ff] font-bold">Account center</p><h1 className="text-3xl font-extrabold mt-2">Personal settings</h1><p className="text-sm text-[#697086] mt-2">Control your identity, AI personalization, notifications and account security.</p></div>
  <div className="grid md:grid-cols-[220px_1fr] gap-5"><aside className="card p-3 h-fit">{tabs.map(([key,label,I])=><button key={key} onClick={()=>setTab(key)} className={`w-full p-3 rounded-xl text-sm font-bold flex gap-2 items-center ${tab===key?'bg-[#04042c] text-white':'text-[#697086] hover:bg-[#f6f7fb]'}`}><I size={16}/>{label}</button>)}</aside>
  <div className="card p-6 space-y-6">{tab==='profile'&&<><div><h2 className="font-extrabold">Profile information</h2><p className="text-xs text-[#8b91a3] mt-1">{user?.email}</p></div><div className="grid sm:grid-cols-2 gap-4">{[['full_name','Full name'],['job_title','Professional title'],['phone','Phone'],['location','Location']].map(([k,l])=><label key={k} className="text-sm font-semibold">{l}<input className="field mt-2" value={(form as any)[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><div className="rounded-2xl bg-[#f7f8fb] p-4"><p className="font-bold text-sm">AI personalization</p><p className="text-xs text-[#697086] mt-1">Your profile fields are used to make resume suggestions more relevant. You remain in control of every generated change.</p></div><div className="border-t border-[#eceef4] pt-5 flex justify-between items-center"><div><p className="font-bold">Current plan</p><p className="text-xs text-[#8b91a3] capitalize">{profile?.plan||'free'} · Monthly credits renew automatically.</p></div><button className="btn btn-primary" onClick={save}><Save size={15}/>{saved?'Saved':'Save changes'}</button></div></>}
  {tab==='notifications'&&<><h2 className="font-extrabold">Notifications</h2>{[['product','Product updates','New features, fixes and workspace improvements'],['weekly','Weekly career digest','Resume health and job-search reminders'],['marketing','Offers & promotions','Occasional product offers and announcements']].map(([k,t,d])=><Toggle key={k} title={t} description={d} value={(notify as any)[k]} onChange={v=>setNotify({...notify,[k]:v})}/>)}<button className="btn btn-primary" onClick={savePrefs}><Check size={15}/> Save preferences</button></>}
  {tab==='privacy'&&<><h2 className="font-extrabold">Privacy & AI controls</h2>{[['analytics','Anonymous product analytics','Help improve reliability and performance'],['aiTraining','Use my data to improve AI','Do not enable this unless you explicitly want to participate'],['publicSharing','Allow public resume links','Controls whether share links can expose your resume']].map(([k,t,d])=><Toggle key={k} title={t} description={d} value={(privacy as any)[k]} onChange={v=>setPrivacy({...privacy,[k]:v})}/>)}<div className="border-t pt-5"><button className="btn btn-soft" onClick={exportData}><Download size={15}/> Export account data</button></div><button className="btn btn-primary" onClick={savePrefs}><Save size={15}/> Save privacy settings</button></>}
  {tab==='security'&&<><h2 className="font-extrabold">Security</h2><p className="text-sm text-[#697086]">Signed in as <b>{user?.email}</b></p><label className="text-sm font-semibold">New password<div className="relative mt-2"><input className="field pr-10" type={showPass?'text':'password'} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/><button type="button" className="absolute right-3 top-3 text-[#697086]" onClick={()=>setShowPass(!showPass)}>{showPass?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></label><button className="btn btn-primary" onClick={changePassword}><KeyRound size={15}/> Update password</button><div className="border-t pt-5"><p className="font-bold text-red-600">Danger zone</p><p className="text-xs text-[#697086] mt-1">Account deletion is intentionally handled through support so resumes and payment records cannot be removed accidentally.</p><button className="btn btn-soft mt-3 text-red-600"><Trash2 size={15}/> Request account deletion</button></div></>}
  {notice&&<p className="text-sm text-[#3047ff]">{notice}</p>}</div></div></div>
}
function Toggle({title,description,value,onChange}:{title:string;description:string;value:boolean;onChange:(v:boolean)=>void}){return <div className="flex items-center justify-between gap-4 border border-[#e7e9f0] rounded-2xl p-4"><div><p className="text-sm font-bold">{title}</p><p className="text-xs text-[#697086] mt-1">{description}</p></div><button onClick={()=>onChange(!value)} className={`w-12 h-7 rounded-full p-1 transition ${value?'bg-[#3047ff]':'bg-[#d9dce5]'}`}><span className={`block w-5 h-5 bg-white rounded-full transition ${value?'translate-x-5':''}`}/></button></div>}
