
import {useState} from 'react';
import {motion} from 'framer-motion';
import {BarChart3,Briefcase,ChevronRight,Cloud,FileText,Grid3X3,IndianRupee,Mail,MessageSquare,Mic2,Sparkles,Target,TrendingUp,Wand2,Search,ShieldCheck} from 'lucide-react';
import type {ViewKey} from '@/components/Sidebar';
import {useAuth} from '@/context/AuthContext';

const tools:{key:ViewKey;name:string;desc:string;icon:any;group:string;kind:'ai'|'tool'}[]=[
 {key:'builder',name:'AI Resume Builder',desc:'Build or import a resume with live premium templates.',icon:FileText,group:'Create',kind:'ai'},
 {key:'analyzer',name:'Resume Intelligence',desc:'Deep content, grammar, impact and formatting audit.',icon:BarChart3,group:'Analyze',kind:'tool'},
 {key:'ats',name:'ATS Score Checker',desc:'Measure parsing, keywords and job-readiness.',icon:Target,group:'Analyze',kind:'tool'},
 {key:'jobmatch',name:'Job Match',desc:'Compare a resume against any job description.',icon:Briefcase,group:'Analyze',kind:'tool'},
 {key:'linkedin',name:'LinkedIn Optimizer',desc:'Improve headline, about, skills and positioning.',icon:Briefcase,group:'Profile',kind:'ai'},
 {key:'coverletter',name:'Cover Letter Studio',desc:'Create tailored letters from your resume and role.',icon:Mail,group:'Create',kind:'ai'},
 {key:'rewrite',name:'AI Rewrite',desc:'Turn weak bullets into measurable achievement statements.',icon:Wand2,group:'Create',kind:'ai'},
 {key:'interview',name:'Interview Coach',desc:'Generate role-specific questions and practice plans.',icon:Mic2,group:'Prepare',kind:'ai'},
 {key:'recruiter',name:'Recruiter Simulation',desc:'See how a recruiter may scan your profile.',icon:Search,group:'Prepare',kind:'tool'},
 {key:'skillgap',name:'Skill Gap Map',desc:'Identify missing capabilities for target roles.',icon:TrendingUp,group:'Prepare',kind:'tool'},
 {key:'heatmap',name:'Resume Heatmap',desc:'Visualize attention, density and section strength.',icon:Grid3X3,group:'Analyze',kind:'tool'},
 {key:'keywords',name:'Keyword Cloud',desc:'Discover important terms and weak keyword coverage.',icon:Cloud,group:'Analyze',kind:'tool'},
 {key:'salary',name:'Salary Predictor',desc:'Estimate market positioning from profile signals.',icon:IndianRupee,group:'Advance',kind:'tool'},
 {key:'careers',name:'Career Path Finder',desc:'Explore adjacent roles and next-step opportunities.',icon:TrendingUp,group:'Advance',kind:'ai'},
 {key:'chat',name:'Resume AI Chat',desc:'Ask questions about your resume and career story.',icon:MessageSquare,group:'Advance',kind:'ai'},
];
export function Workspace({onNavigate}:{onNavigate:(v:ViewKey)=>void}){const{profile}=useAuth();const[q,setQ]=useState('');const[active,setActive]=useState('All');
 const groups=['All','Create','Analyze','Profile','Prepare','Advance'];const filtered=tools.filter(t=>(active==='All'||t.group===active)&&`${t.name} ${t.desc}`.toLowerCase().includes(q.toLowerCase()));
 const launch=(t:any)=>onNavigate(t.key);
 return <div className="space-y-6 reveal"><div className="dark-glass rounded-[26px] p-7 md:p-9 text-white relative overflow-hidden"><div className="absolute -right-10 -top-20 w-64 h-64 rounded-full bg-[#3047ff]/25 blur-3xl"/><div className="relative"><span className="text-xs tracking-[.22em] uppercase text-white/50 font-bold">QuadraResume Studio</span><h1 className="text-3xl md:text-4xl font-extrabold mt-3">One workspace for your entire career.</h1><p className="text-sm text-white/55 max-w-2xl mt-3">Build the document, test it against ATS systems, tailor it to jobs, strengthen your LinkedIn and rehearse for interviews — without leaving the studio.</p><div className="mt-6 flex flex-col sm:flex-row gap-3"><div className="relative flex-1 max-w-lg"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-white/35" size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full bg-white/10 border border-white/10 rounded-xl px-10 py-3 text-sm text-white outline-none placeholder:text-white/35" placeholder="Search a career tool…"/></div><button onClick={()=>onNavigate('builder')} className="btn bg-white text-[#04042c]"><Sparkles size={15}/> Build a resume</button></div></div></div>
 <div className="grid lg:grid-cols-[1.25fr_.75fr] gap-4"><div className="card overflow-hidden relative min-h-[180px]"><img src="/media/career-hero.svg" alt="AI career workspace" className="absolute inset-0 w-full h-full object-cover opacity-35"/><div className="relative p-6 bg-gradient-to-r from-white via-white/90 to-transparent h-full"><p className="text-[10px] uppercase tracking-[.22em] text-[#3047ff] font-extrabold">Career intelligence layer</p><h2 className="text-2xl font-extrabold mt-2 max-w-xl">Stop switching between tools. Build, score, tailor and prepare in one flow.</h2><p className="text-xs text-[#697086] mt-2 max-w-xl">Every tool works from your saved resume, so your information stays consistent while you iterate.</p></div></div><div className="dark-glass rounded-[20px] overflow-hidden text-white"><img src="https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=900" alt="AI career workspace" className="w-full h-44 object-cover opacity-75"/><div className="p-4"><p className="text-xs font-bold">Career intelligence workspace</p><p className="text-[11px] text-white/50 mt-1">A focused command center for every stage of your application.</p></div></div></div>
 <div className="flex gap-2 overflow-auto pb-1">{groups.map(g=><button key={g} onClick={()=>setActive(g)} className={`px-4 py-2 rounded-full text-xs font-bold whitespace-nowrap ${active===g?'bg-[#04042c] text-white':'bg-white border border-[#e5e7ef] text-[#697086]'}`}>{g}</button>)}</div>
 <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map((t,i)=>{const I=t.icon;return <motion.button whileHover={{y:-4}} key={t.key} onClick={()=>launch(t)} className="card p-5 text-left group"><div className="flex items-start justify-between"><div className="w-11 h-11 rounded-xl bg-[#f0f1ff] flex items-center justify-center"><I size={19} className="text-[#3047ff]"/></div><span className={`text-[9px] uppercase tracking-widest font-bold px-2 py-1 rounded-full ${t.kind==='ai'?'bg-[#eef0ff] text-[#3047ff]':'bg-[#f4f5f7] text-[#777e90]'}`}>{t.kind==='ai'?'AI':'Tool'}</span></div><h3 className="font-extrabold mt-5">{t.name}</h3><p className="text-xs text-[#7d8396] mt-1 leading-5">{t.desc}</p><span className="mt-5 text-xs font-bold flex items-center gap-1 text-[#3047ff]">Open studio <ChevronRight size={13} className="group-hover:translate-x-1 transition"/></span></motion.button>})}</div>
 <div className="card p-5 flex flex-col md:flex-row items-start md:items-center justify-between gap-4"><div className="flex gap-3"><div className="w-10 h-10 rounded-xl bg-[#04042c] text-white flex items-center justify-center"><ShieldCheck size={18}/></div><div><p className="font-extrabold">Your workspace is private</p><p className="text-xs text-[#8b91a3] mt-1">Resume records are scoped to your account with Supabase row-level security.</p></div></div><button onClick={()=>onNavigate('settings')} className="btn btn-soft">Privacy settings</button></div>
 </div>}
