import { useEffect, useState, type FormEvent } from 'react';
import { ArrowLeft, Loader2, Sparkles, Mail, ShieldCheck } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

export function AuthScreen(){
 const{signIn,signUp,signInWithGoogle,sendPasswordReset,updatePassword}=useAuth();
 const[signup,setSignup]=useState(false);const[forgot,setForgot]=useState(false);const[reset,setReset]=useState(false);
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[confirm,setConfirm]=useState('');const[name,setName]=useState('');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[success,setSuccess]=useState('');
 useEffect(()=>{const params=new URLSearchParams(window.location.search);if(params.get('reset')==='1')setReset(true)},[]);
 const submit=async(e:FormEvent)=>{e.preventDefault();setBusy(true);setError('');setSuccess('');try{
   if(forgot){const r=await sendPasswordReset(email);if(r.error)setError(r.error);else setSuccess('Password reset instructions were sent to your email. Check your inbox and open the secure link.');return}
   if(reset){if(password!==confirm){setError('Passwords do not match.');return}if(password.length<8){setError('Use at least 8 characters.');return}const r=await updatePassword(password);if(r.error)setError(r.error);else{setSuccess('Password updated successfully. You can now continue to your account.');setTimeout(()=>{window.history.replaceState({},'',window.location.pathname);window.location.reload()},1000)}return}
   const r=signup?await signUp(email,password,name):await signIn(email,password);if(r.error)setError(r.error);else if(signup)setSuccess('Account created. Check your email if email confirmation is enabled.');
 }finally{setBusy(false)}};
 const title=reset?'Create a new password':forgot?'Recover your account':signup?'Start building':'Welcome back';
 return <div className="min-h-screen bg-[#f8f9fc] flex items-center justify-center p-5"><div className="w-full max-w-5xl grid lg:grid-cols-2 card overflow-hidden"><div className="dark-glass text-white p-8 md:p-12 min-h-[620px] flex flex-col justify-between"><div><div className="w-11 h-11 rounded-xl bg-white text-[#04042c] flex items-center justify-center"><Sparkles/></div><p className="text-xs uppercase tracking-[.22em] text-white/40 font-bold mt-10">QuadraResume</p><h1 className="text-4xl font-extrabold mt-3">Your career studio is ready.</h1><p className="text-white/50 text-sm leading-6 mt-4">Premium resumes, AI career intelligence, ATS optimization and a private workspace designed around your career data.</p><div className="mt-10 space-y-3 text-sm text-white/70"><p className="flex gap-2"><ShieldCheck size={17}/> Secure Supabase authentication</p><p className="flex gap-2"><Sparkles size={17}/> AI-assisted career tools</p><p className="flex gap-2"><Mail size={17}/> Google and email sign-in</p></div></div><p className="text-xs text-white/30">QuadraFroyn Solutions · 2026</p></div>
 <div className="p-8 md:p-12 flex items-center"><form onSubmit={submit} className="w-full max-w-md mx-auto"><button type="button" onClick={()=>{setForgot(false);setReset(false);setSignup(false);setError('');setSuccess('')}} className="text-xs font-bold text-[#697086] flex items-center gap-1 mb-6"><ArrowLeft size={13}/> {reset||forgot?'Back to sign in':'QuadraResume'}</button><p className="text-xs uppercase tracking-[.2em] text-[#3047ff] font-bold">{reset?'SECURE RESET':forgot?'ACCOUNT RECOVERY':signup?'CREATE ACCOUNT':'SIGN IN'}</p><h2 className="text-3xl font-extrabold mt-3">{title}</h2><p className="text-sm text-[#697086] mt-2">{reset?'Choose a strong password for your account.':forgot?'Enter your existing email address and we will send a secure reset link.':signup?'Your first account becomes the platform owner automatically.':'Continue to your private resume studio.'}</p>
 {!reset&&<label className="text-xs font-bold block mt-7">Email<input className="field mt-2" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label>}
 {signup&&!forgot&&!reset&&<label className="text-xs font-bold block mt-5">Full name<input className="field mt-2" value={name} onChange={e=>setName(e.target.value)} required/></label>}
 {!forgot&&<label className="text-xs font-bold block mt-5">{reset?'New password':'Password'}<input className="field mt-2" type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength={8} required/></label>}
 {reset&&<label className="text-xs font-bold block mt-5">Confirm password<input className="field mt-2" type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} minLength={8} required/></label>}
 {error&&<p className="text-sm text-red-600 mt-4">{error}</p>}{success&&<p className="text-sm text-emerald-700 mt-4">{success}</p>}
 <button disabled={busy} className="btn btn-primary w-full mt-6">{busy?<Loader2 size={16} className="animate-spin"/>:null}{reset?'Update password':forgot?'Send reset link':signup?'Create account':'Sign in'}</button>
 {!forgot&&!reset&&<><div className="relative my-5"><div className="border-t border-[#e7e9f0]"/><span className="absolute left-1/2 -translate-x-1/2 -top-2.5 bg-white px-3 text-[10px] font-bold text-[#8b91a3]">OR</span></div><button type="button" onClick={async()=>{setBusy(true);setError('');const r=await signInWithGoogle();if(r.error)setError(r.error);setBusy(false)}} className="btn btn-soft w-full"><span className="font-black text-base">G</span> Continue with Google</button><button type="button" onClick={()=>{setForgot(true);setSignup(false);setError('');setSuccess('')}} className="w-full text-sm font-bold text-[#3047ff] mt-5">Forgot password?</button><button type="button" onClick={()=>{setSignup(!signup);setForgot(false);setError('');setSuccess('')}} className="w-full text-sm font-bold text-[#697086] mt-3">{signup?'Already have an account? Sign in':'New here? Create your account'}</button></>}
 </form></div></div></div>
}
