
import {motion} from 'framer-motion';
import {LayoutDashboard,Sparkles,Settings,CreditCard,ShieldCheck,LogOut,ChevronRight,FileText} from 'lucide-react';
import {useAuth} from '@/context/AuthContext';
import {useResumes} from '@/context/ResumeContext';
export type ViewKey='dashboard'|'workspace'|'builder'|'analyzer'|'ats'|'jobmatch'|'coverletter'|'interview'|'skillgap'|'history'|'linkedin'|'careers'|'chat'|'templates'|'recruiter'|'heatmap'|'salary'|'keywords'|'rewrite'|'settings'|'pricing'|'admin';
const base=[['dashboard','Dashboard',LayoutDashboard],['builder','AI Resume Builder',FileText],['workspace','AI Workspace',Sparkles],['pricing','Plans & billing',CreditCard],['settings','Personal settings',Settings]] as const;
export function Sidebar({current,onNavigate}:{current:ViewKey;onNavigate:(v:ViewKey)=>void}){const{user,profile,signOut}=useAuth();const{resumes}=useResumes();return <aside className="fixed left-0 top-0 bottom-0 w-[250px] bg-[#04042c] text-white z-40 hidden lg:flex flex-col">
 <div className="p-5 border-b border-white/10"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-xl bg-white text-[#04042c] flex items-center justify-center"><Sparkles size={18}/></div><div><p className="font-extrabold">QuadraResume</p><p className="text-[9px] tracking-[.2em] text-white/35 uppercase">Career intelligence</p></div></div></div>
 <div className="px-3 py-4 flex-1"><p className="px-3 text-[9px] uppercase tracking-[.2em] text-white/30 font-bold mb-2">Workspace</p>{base.map(([key,label,I])=><Nav key={key} active={current===key} icon={I} label={label} onClick={()=>onNavigate(key)}/>)}{profile?.role==='admin'&&<><p className="px-3 text-[9px] uppercase tracking-[.2em] text-white/30 font-bold mt-6 mb-2">Management</p><Nav active={current==='admin'} icon={ShieldCheck} label="Admin console" onClick={()=>onNavigate('admin')}/></>}</div>
 <div className="p-3 border-t border-white/10"><div className="rounded-xl bg-white/5 p-3 mb-2"><p className="text-xs font-bold truncate">{profile?.full_name||user?.email}</p><p className="text-[10px] text-white/35 mt-1">{resumes.length} saved resumes · <span className="capitalize">{profile?.plan||'free'}</span></p></div><button onClick={signOut} className="w-full flex items-center gap-2 px-3 py-2.5 text-xs font-bold text-white/50 hover:text-white rounded-lg hover:bg-white/5"><LogOut size={14}/> Sign out</button></div>
 </aside>}
function Nav({active,icon:Icon,label,onClick}:{active:boolean;icon:any;label:string;onClick:()=>void}){return <button onClick={onClick} className={`w-full relative flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-semibold mb-1 ${active?'bg-white text-[#04042c]':'text-white/55 hover:bg-white/5 hover:text-white'}`}>{active&&<motion.span layoutId="activeNav" className="absolute left-0 w-1 h-6 bg-[#3047ff] rounded-r-full"/>}<Icon size={16}/><span className="flex-1 text-left">{label}</span>{active&&<ChevronRight size={13}/>}</button>}
